#!/usr/bin/env bash

set -e
set -x

if [ ! "$EUID" -eq 0 ]; then
  echo "Run as root!"
  exit 1
fi

if [ ! -d GadgetDeck ]; then
  mkdir GadgetDeck
  cd GadgetDeck
  wget https://github.com/Frederic98/GadgetDeck/releases/download/V0.1/GadgetDeck.zip
  unzip GadgetDeck.zip
else
  cd GadgetDeck
fi

python -m venv venv
make
make install

# cp -r GadgetDeck /usr/share/gadget-deck/
mkdir -p program
chmod +x program/GadgetDeck
sudo -u deck bash -c "steamos-add-to-steam $(pwd)/program/GadgetDeck"

